name: Provider Request
description: Request a new platform example to be added to dlkitgo
title: "[Provider Request]: "
labels: ["provider request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a new provider!
        
        Please fill out the information below to help us understand your request.
        
  - type: input
    id: platform-name
    attributes:
      label: Platform Name
      description: What platform would you like to see added?
      placeholder: "e.g., YouTube, Twitter, TikTok"
    validations:
      required: true
      
  - type: input
    id: platform-url
    attributes:
      label: Platform URL
      description: What is the main URL of the platform or service you're requesting? (e.g., https://fastvideosave.net/)
      placeholder: "https://www.example.com"
    validations:
      required: true
      
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: What would you use this platform example for?
      placeholder: "Describe what you'd like to do with this platform..."
    validations:
      required: true
